using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace radar_drone_App_User
{
    class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string uuid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }

    }
}
